### ISSUE TITLE
Not installing into PCL(i.e. Portable Class Library project) on Cross platform app

### ISSUE THREAD

**Issue by sigurdurb** [nCubed/TheMovieDbWrapper#15]
I am trying to install this package with nuget into a Cross-Platform Blank Portable app,
It does install fine into the .Droid and .iOS but when I try to install with nuget into the PCL(Portable Library) project it always gives me the following error. Even if I change Targets so the .NETPortable goes up to v4.5=Profile259 it gives me the same Error.

```

Error 	Could not install package 'TheMovieDbWrapper 0.8.0'. 
You are trying to install this package into a project that targets '.NETPortable,Version=v4.0,Profile=Profile24', 
but the package does not contain any assembly references or content files 
that are compatible with that framework. For more information, contact the package author.
```

**Comment by nCubed** [comment]
We recently converted the project to be cross platform compatible following the .netstandard protocol which simplified the NuGet packaging. Looks like we may have missed something in our testing.

Would you mind providing a detailed set of reproduction steps? i.e., VS version, project type, etc...

Thanks!

**Comment by sigurdurb** [comment]
Yes, this is an issue on my setup where I have Visual Studio 2015 Enterprise on a Windows 10 Pro. My friend is also having the same issue on a Visual Studio 2015 running Windows 7.
But it works adding to the PCL on a same project on a Macbook Pro(El-Capitan) with Xamarin Studio 6.1.2(Build 44)

**Comment by nCubed** [comment]
Would it be possible to provide a complete step-by-step reproduction? i.e.,

1. Open Visual Studio 2015
2. Create XYZ project w/ a target of .NET v4
3. Right Click Project in VS > Properties > Change project type
4. Add NuGet package reference (fails? succeeds?)

This will help us quite a bit to better understand the exact steps you are using as we've been unable to reproduce this error on our own.

Thanks!

**Comment by sigurdurb** [comment]
The target framework was always .NET v.4.5 but the .NETPortable version changed.
I managed to analyze the problem.
First when I create a new project it gives me this error
```
Error		Could not install package 'TheMovieDbWrapper 0.8.0'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile259', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```
With these Target configurations for the PCL project
![notworking](https://cloud.githubusercontent.com/assets/10588202/21019057/192b504a-bd67-11e6-8939-56f35b40d6f3.PNG)
Then I unmarked the box for Windows Phone Silverlight 8.1 and then It would let me install it:
![workingtargets](https://cloud.githubusercontent.com/assets/10588202/21019296/cbeb0784-bd67-11e6-8f9d-d175c5f864a8.PNG)

If I tried adding the MovieDBWrapper to the PCL and then add the Windows Phone Silverlight 8 back in I got an error about nuget 3 package support:
![errorwinnuget](https://cloud.githubusercontent.com/assets/10588202/21019248/a42f2626-bd67-11e6-8297-aed4beb0fd2d.PNG)

So then I went back to my old project with the original error
These were the settings I had that gave me the same error as above but with 
'.NETPortable,Version=v4.0,Profile=Profile24'
![notworkingpcltargetsforwrapper1](https://cloud.githubusercontent.com/assets/10588202/21019365/1b959132-bd68-11e6-8794-fa74f7949910.PNG)

but changing them to these made it work
![workingpcltargetsforwrapper](https://cloud.githubusercontent.com/assets/10588202/21019582/f520464a-bd68-11e6-9d3d-b9b14fd8d303.PNG)

**Comment by nCubed** [comment]
OK, this make more sense now. The out of the box portable class library is not supported right now; the out of the box PCL cross-platform support is a known pain point for many library devs.

Thankfully, this is easy to resolve by re-targeting your project. Create the project the exact same way as before, but before you add any NuGet packages, right click on the project > properties (same as you did before). But, instead of clicking the "Change..." button, click the "Target .NET Platform Standard" link.

![01-targeting-support](https://cloud.githubusercontent.com/assets/1033214/21020500/6170103e-bd3a-11e6-8560-1ad7b797b7f8.png)

After clicking the "Target .NET Platform Standard" link, confirm the following:
![02-targeting-support-confirm](https://cloud.githubusercontent.com/assets/1033214/21020512/7300d0c2-bd3a-11e6-8755-8351fd87a3f1.png)

By default, .netstandard 1.1 should be selected:
![03-targeting-support-netstandard1-1](https://cloud.githubusercontent.com/assets/1033214/21020524/7c05558a-bd3a-11e6-9a1b-684b7d9ec84a.png)

The above targeting of .netstandard is the current path forward for all cross-platform libraries. I believe in VS 2017 the project management will be much more straight-forward than the current ecosystem.

Can you post back if this works for you?

**Comment by sigurdurb** [comment]
Creating a new PCL project and changing to .NETStandard 1.1 and then installing TheMovieDbWrapper works at my end. Did not know about the .NETStandard. Thanks for your help.
